### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by rajajlidi** [Zimbra-Community/js-zimbra#10]
can anyone help me when i run the project the server cruch 

this is my file route

'use strict';
var express= require('express');
var router= express.Router();
var jszimbra = require('js-zimbra');
var winston = require('winston');

winston.loggers.add("js-zimbra", {console: {level: "error"}});

var comm = new jszimbra.Communication({
    url: "https://your-zimbra-server/service/soap"
});

comm.auth({
    "username": "zimbrauser",
    "secret": "fowunfguipht542uip5nupfnru2ütu3ü2brtufwe"
}, function (err) {

    comm.getRequest({
        isBatch: true
    }, function (err, req) {

        req.addRequest({
            name: "GetAccountInfoRequest",
            namespace: "zimbraAccount",
            params: {
                "account": {
                    "by": "name",
                    "_content": "zimbraid"
                }
            }
        }, function (err, reqid) {

            // reqid holds the id of the added request and can be used to
            // identify the request in the response

            req.addRequest({
                name: "GetAccountInfoRequest",
                namespace: "zimbraAccount",
                params: {
                    "account": {
                        "by": "name",
                        "_content": "zimbraid"
                    }
                }
            }, function (err, reqid) {

                comm.send(req, function (err, response) {

                    // Shows an array with two members

                    console.log(response.GetAccountInfoRequest);

                });

            });

        });
});
    done();

});

module.exports=router;

**Comment by dploeger** [comment]
What do you mean by "the server cruch"? What errors are you getting. The source looks fine from a first look.

**Comment by rajajlidi** [comment]
when i run i see this result in my console and ater that it stop runing

![c](https://user-images.githubusercontent.com/18144469/26943438-f4dca3e0-4c5b-11e7-89ba-bfbdd3d35490.PNG)

**Comment by dploeger** [comment]
Seems as if Zimbra delivers an empty response upon your auth request. What does the Zimbra mailbox.log say at that time?

**Comment by rajajlidi** [comment]
it's empty too , please i have question how can i find the username and secret pass to authenticate to zimbra soap api?

**Comment by rajajlidi** [comment]
it log 
debug: Adding new request to stack: {"params":{"account":{"by":"name","_content":"zimbrauser"},"preauth":{"timestamp":1496944096775,"expires":0,"_content":"019bb2f8322fbd9887d29e8ccbf950b2fb48e2f9"},"_jsns":"urn:zimbraAccount"},"namespace":"zimbraAccount","name":"AuthRequest"}
debug: Sending AuthRequest
debug: CommunicationApi#send called
debug: Fetching request pojo from request stack
debug: RequestApi#getRequest called
debug: Building up request pojo
debug: Returning request pojo: {"Header":{"context":{"_jsns":"urn:zimbra","format":{"type":"js"}}},"Body":{"AuthRequest":{"account":{"by":"name","_content":"zimbrauser"},"preauth":{"timestamp":1496944096775,"expires":0,"_content":"019bb2f8322fbd9887d29e8ccbf950b2fb48e2f9"},"_jsns":"urn:zimbraAccount"}}}
debug: Sending request to Zimbra: {"Header":{"context":{"_jsns":"urn:zimbra","format":{"type":"js"}}},"Body":{"AuthRequest":{"account":{"by":"name","_content":"zimbrauser"},"preauth":{"timestamp":1496944096775,"expires":0,"_content":"019bb2f8322fbd9887d29e8ccbf950b2fb48e2f9"},"_jsns":"urn:zimbraAccount"}}}

**Comment by dploeger** [comment]
The user is a normal Zimbra user - usually an email address. The secret can be the password of that user (than there has to be an additional parameter "isPassword": true) or the preauth key of the domain the user is in. (see https://wiki.zimbra.com/wiki/Preauth)
