### ISSUE TITLE
Change NPM Owner

### ISSUE THREAD

**Issue by dploeger** [Zimbra-Community/js-zimbra#11]
@barrydegraaff I'm currently still the NPM-owner for js-zimbra. Do you have an NPM login or do you like to create an organization-login for zimbra-community so I could transfer the ownership to that account?

**Comment by ghost** [comment]
I created the zetalliance org on NPM, and made you an admin there too, so you should be able to transfer the ownership.

Thanks for reaching out!

**Comment by dploeger** [comment]
Okay, I added the package with read-write-access to the developers team of the org.

However, I'm still the owner of the repo. Do you have an account on NPM? I'd like to transfer the package completely.

**Comment by ghost** [comment]
Yeah, it's barrydegraaff

**Comment by ghost** [comment]
You can do something like `npm owner rm ploeger js-zimbra` if you want to be forgotten.

**Comment by dploeger** [comment]
Yes, I know. But it somehow doesn't work (npm says "Forbidden"). But you're an owner now, too. Perhaps you can remove me. But, I'm fine with this setup now. Thanks!

**Comment by ghost** [comment]
OK thanks
