### ISSUE TITLE
Error: Cannot find module 'js-zimbra' constant problem

### ISSUE THREAD

**Issue by houssem-yahiaoui** [Zimbra-Community/js-zimbra#2]
Hello, 

While i'm using this module, and while i'm instaishiating the module, once i run my code i keep on getting the Error: Cannot find module 'js-zimbra' error, i don't know where the problem is comming from, any suggestions ?

**Comment by pbruna** [comment]
Can you paste your code

Saludos. 

---

Patricio Bruna
CEO - IT Linux 
(+56-2) 2902 3001
(+56-9) 8899 6618
www.itlinux.cl / blog.itlinux.cl

Correo enviado a través de
ZBox: Correo y Colaboración en la Nube

**Comment by houssem-yahiaoui** [comment]
I finally got the problem, i will pull request it, there's some major naming troubles in the package.

Houssem.

**Comment by ghost** [comment]
Looking forward to your PR.
