### ISSUE TITLE
error while proxying request to target server: Connection reset

### ISSUE THREAD

**Issue by houssem-yahiaoui** [Zimbra-Community/js-zimbra#6]
Hello, 

I'm trying to send an email using the js-zimbra module, but i keep on getting an error that i didn't knew how to fix, 

her's my code : 

``` javascript
var z = require('js-zimbra');

var comm = new z.Communication({
    url: "resource"
});

// Authenticate

comm.auth({
    "username": "user",
    "secret": "pass",
    "isPassword": true
}, function(err) {
    if (err) {
        // An error occured authenticating
    }
        // Now, carry on creating requests and sending them
    comm.getRequest({}, function(err, req) {
        if (err) {
            // Can't create a new request
        }
        req.addRequest({
            name: "SearchRequest",
            namespace: "zimbraMail",
            params: {
                "SearchRequest" : {
                    "types" : "message",
                    "fetch" : "all"     
                },
                "query": {
                    "_content": "in:inbox"
                }
            }
        }, function(err) {

            if (err) {
                console.log('err', err);
            }
            comm.send(req, function(err, res) {
                if (err) {
                    console.log('err', err);
                }
                console.log(res);
            })
        })
    })
});
```

then i got the following error : 

error: Received server error: {"Code":{"Value":"soap:Receiver"},"Reason":{"Text":"error while proxying request to target server: Connection reset"},"Detail":{"Error":{"Code":"service.PROXY_ERROR","Trace":"qtp509886383

is there any explanation of fix to this error ?

**Comment by dploeger** [comment]
Urgh. That seems to be an error in Zimbra. You should check the mailbox.log for this one.

**Comment by dploeger** [comment]
I don't believe, that this is because auf js-zimbra, so I will close this issue for the time being.

**Comment by rajajlidi** [comment]
hello @houssem-yahiaoui  i'm working in one project with the same feature zimbra and i have the same problem if did you find solution please tell me how can i solve my problem too
