### ISSUE TITLE
How to specify Request attribute in parrent node

### ISSUE THREAD

**Issue by houssem-yahiaoui** [Zimbra-Community/js-zimbra#8]
Hello, 

I do have this problem where i don't know how to set the parent node attribute, I have the following example : 

``` xml
<urn2:SearchRequest types="message" fetch="all">
         <urn2:query>in:inbox</urn2:query>
</urn2:SearchRequest>
```

so my call is like this one : 

``` javascript
req.addRequest({
                name: "SearchRequest",
                namespace: "zimbraMail",
                params: {
                    "SearchRequest": {
                        "types": "message",
                        "fetch": "all"
                    },
                    "query" : {
                        "_content" : "in:inbox"
                    }
                }
})
```

Is it correct ??? if not what is the right way.

**Comment by dploeger** [comment]
The correct way would be:

```
req.addRequest({
                name: "SearchRequest",
                namespace: "zimbraMail",
                params: {
                    "SearchRequest": {
                        "types": "message",
                        "fetch": "all"
                        "query" : {
                           "_content" : "in:inbox"
                        } 
                    }
                }
})
```

The Zimbra JSON-Format is described here: https://github.com/Zimbra-Community/python-zimbra#used-dictionary

Maybe, we should at that part to the js-zimbra README as well.

**Comment by houssem-yahiaoui** [comment]
@dploeger  weirdly enough it's not working...

**Comment by dploeger** [comment]
What isn't working? Do you get an error message?

**Comment by houssem-yahiaoui** [comment]
@dploeger  i'm doing a batch request and here's the output in my cmd : 

debug: Building new Response object
debug: Instantiating new response object
debug: Validating options
debug: ResponseApi#_createResponseView called
debug: RequestApi#isBatch called
debug: Handling batch response
debug: Collecting batch responses
ResponseApi {
  options:
   { request: RequestApi { options: [Object], requests: [Object], batchId: 3 },
     response: { BatchResponse: [Object] } },
  response:
   { '1': { GetAccountInfoResponse: [Object] },
     '2': { Fault: [Object] },
     undefined: undefined },
  isBatch: true }

Very weird response indeed. is there any solution ?? i really need this module.

**Comment by dploeger** [comment]
Oh, wait. Try this:

```
req.addRequest({
                name: "SearchRequest",
                namespace: "zimbraMail",
                params: {
                        "types": "message",
                        "fetch": "all"
                        "query" : {
                           "_content" : "in:inbox"
                        } 
                }
})
```

You don't have to repeat "SearchRequest" in params. The params are starting at SearchRequest.

**Comment by houssem-yahiaoui** [comment]
@dploeger, Still same problem nothing, i don't know how to fix that...

**Comment by dploeger** [comment]
The second request in your batch request responded with a fault. What's the fault saying? You can use response.get(1) to get that specific response object and check the error code in there.

It seems, that the current state of js-zimbra misses the fault-specific functions like "isFault" and "getFaultMessages" from python-zimbra. I will be using js-zimbra in a few weeks for a project again and will be optimizing it then.

If you have the time to implement these methods, pull requests will be accepted. ;-)

**Comment by dploeger** [comment]
Made a feature request for it in #9.
